# これがルートの設定ファイル（上位ディレクトリを検索しない）
root: true

extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
  - next
  - next/core-web-vitals
  - prettier
  - 'plugin:prettier/recommended'

parser: '@typescript-eslint/parser'

rules:
  'prettier/prettier': 'error'

parserOptions:
  project: ./tsconfig.json

ignorePatterns: '**/*.js'
