inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-rails
  # 細かすぎるので一旦無効化
  # - rubocop-rspec

# AllCopsオプションで全てのCopsを対象にできる
AllCops:
  NewCops: enable

Style/FrozenStringLiteralComment:
  Enabled: false

Documentation:
  Enabled: false