inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-rails
  # 細かすぎるので一旦無効化
  # - rubocop-rspec

# AllCopsオプションで全てのCopsを対象にできる
AllCops:
  NewCops: enable

Style/FrozenStringLiteralComment:
  Enabled: false

Documentation:
  Enabled: false

# 日本語だと「〜の場合」になるので suffix でないと対応できない
RSpec/ContextWording:
  Enabled: false
