name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
        options: --health-cmd "mysqladmin ping" --health-interval 10s --health-timeout 5s --health-retries 10
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2.2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Build and test
      env:
        TZ: Asia/Tokyo
      run: |
        docker build -t my-rails-app .
        docker run -d -p 3000:3000 my-rails-app

        # Wait for the Rails server to start
        sleep 20

        # Run Rubocop
        docker exec -it $(docker ps -q) bundle exec rubocop

        # Run RSpec tests
        docker exec -it $(docker ps -q) bundle exec rspec

    - name: Deploy to GitHub Pages
      env:
        TZ: Asia/Tokyo
        JEKYLL_ENV: production
      run: |
        docker build -t my-rails-app .
        docker run -d -p 4000:4000 my-rails-app

        # Wait for the Jekyll server to start
        sleep 20

        # Optionally, build your static site assets here, e.g., using webpacker or any other build tool your app requires

        # Deploy to GitHub Pages (replace `gh-pages` with your target branch)
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "GitHub Actions"
        git checkout -B gh-pages
        git add -f public # Add your static site assets or any other files to be deployed
        git commit -m "Deploy static site assets to GitHub Pages"
        git push -f origin gh-pages
